// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbtJvjuyzZInlt3Pm0V8S_nklc4XgI1ek',
    appId: '1:181945947317:web:9fa31db08b65bdc22ddafc',
    messagingSenderId: '181945947317',
    projectId: 'digify-8c92d',
    authDomain: 'digify-8c92d.firebaseapp.com',
    storageBucket: 'digify-8c92d.firebasestorage.app',
    measurementId: 'G-65PXKZVTSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFo56skqQlx2bON19dwu36vGpLiJYHvY',
    appId: '1:181945947317:android:5ccb5e292565a1262ddafc',
    messagingSenderId: '181945947317',
    projectId: 'digify-8c92d',
    storageBucket: 'digify-8c92d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkozzhG5QpfaDIwBdjPEd9M_MW9jMXqm4',
    appId: '1:181945947317:ios:3e87682ea92b87132ddafc',
    messagingSenderId: '181945947317',
    projectId: 'digify-8c92d',
    storageBucket: 'digify-8c92d.firebasestorage.app',
    iosBundleId: 'com.example.digify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkozzhG5QpfaDIwBdjPEd9M_MW9jMXqm4',
    appId: '1:181945947317:ios:3e87682ea92b87132ddafc',
    messagingSenderId: '181945947317',
    projectId: 'digify-8c92d',
    storageBucket: 'digify-8c92d.firebasestorage.app',
    iosBundleId: 'com.example.digify',
  );
}
